### ISSUE TITLE
Investigate TcpListener::try_clone test failures

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1074]
Pr #1070 is going to add (or added, depending on when you read this) two testing involving `TcpListener::try_clone` `try_clone_same_poll` and `try_clone_different_poll`, which only fails on Windows. Figure out why.

/cc @PerfectLaugh

**Comment by dtacalau** [comment]
I've modified try_clone_different_poll test to the simplest form that is still failing: one poll, one listener, two streams.

Problem:
The test below fails on the second  expect_events assert. If I enable the "reregister", after the second stream is started, the test won't fail.
```
#[test]
//#[cfg_attr(windows, ignore = "fails on Windows, see #1073")]
fn tcp_listener_two_streams() {
    let (mut poll1, mut events) = init_with_poll();

    let listener1 = TcpListener::bind(any_local_address()).unwrap();
    let address = listener1.local_addr().unwrap();

    let barrier = Arc::new(Barrier::new(3));
    let thread_handle1 = start_connections(address, 1, barrier.clone());

    poll1
        .registry()
        .register(&listener1, ID1, Interests::READABLE)
        .unwrap();

    expect_events(
        &mut poll1,
        &mut events,
        vec![ExpectEvent::new(ID1, Interests::READABLE)],
    );
   
    let (stream, peer_address) = listener1.accept().expect("unable to accept connection");
    assert!(peer_address.ip().is_loopback());
    assert_eq!(stream.peer_addr().unwrap(), peer_address);
    assert_eq!(stream.local_addr().unwrap(), address);

    let thread_handle2 = start_connections(address, 1, barrier.clone());
/*
    poll1
        .registry()
        .reregister(&listener1, ID1, Interests::READABLE)
        .unwrap();*/

    expect_events(
        &mut poll1,
        &mut events,
        vec![ExpectEvent::new(ID1, Interests::READABLE)],
    );

    assert_would_block(listener1.accept());
    assert!(listener1.take_error().unwrap().is_none());

    barrier.wait();
    thread_handle1.join().expect("unable to join thread");
    thread_handle2.join().expect("unable to join thread");
} 
```

Cause: 
The test fails because, on Windows, mio simulates Edge-triggered behavior, the interests are removed after first poll call, subsequent polls will need to have interests set again, one way being reregister the socket.

```
selector.rs
...
        afd_events &= self.user_evts;
...
        if (afd_events & interests_to_afd_flags(Interests::READABLE)) != 0 {
            self.user_evts &= !(interests_to_afd_flags(Interests::READABLE));
        }
...
```

self.user_evts needs reregister to be set to inital value
If I disable line ```            self.user_evts &= !(interests_to_afd_flags(Interests::READABLE));``` the test won't fail even w/o reregister, but then it won't be edge triggered :). 
Solution:
1. Use reregister. This would seem weird, it would needed only on windows, and it would lead to inconsistent behavior in case someone forgets to call reregister in the right place.
or
2. A safer approach might be to have the API reset the user_evts interests. For instance, for the test above, listener1.accept() could reset it. So TcpStream/TcpListener API would be, by design, responsible for reseting the interests.

**Comment by Thomasdezeeuw** [comment]
@dtacalau thanks for looking into this. Can you see if https://github.com/tokio-rs/mio/pull/1112 changes anything? And if not, can you also try with the following patch applied:

```diff
diff --git a/src/sys/windows/mod.rs b/src/sys/windows/mod.rs
index 0a6eff7..247e5e0 100644
--- a/src/sys/windows/mod.rs
+++ b/src/sys/windows/mod.rs
@@ -31,6 +31,8 @@ macro_rules! try_io {
             if e.kind() == io::ErrorKind::WouldBlock {
                 $self.io_blocked_reregister()?;
             }
+        } else {
+            $self.io_blocked_reregister()?;
         }
         result
     }};
```

@PerfectLaugh mentioned in the pr that it might be needed to reregister interests when the operation succeeded here: https://github.com/tokio-rs/mio/pull/1112#discussion_r340302964, but then the CI failed. So maybe it's only needed for the `TcpListener` and not the other types?

**Comment by dtacalau** [comment]
> @dtacalau thanks for looking into this. Can you see if #1112 changes anything? 
@Thomasdezeeuw  I've checked try_clone tests using the windows cleanup branch https://github.com/Thomasdezeeuw/mio/tree/win-cleanup, and I got same results, tests still fail in the same way as in my previous comment. If I use reregister before the second expect_events test will not fail.

>And if not, can you also try with the following patch applied:
> 
It stil fails using the patch on your branch. So, same behavior as above.

> 
> @PerfectLaugh mentioned in the pr that it might be needed to reregister interests when the >operation succeeded here: [#1112 (comment)](https://github.com/tokio->rs/mio/pull/1112#discussion_r340302964), but then the CI failed. So maybe it's only needed for the >`TcpListener` and not the other types?
That was my conclusion too, using reregister the test won't fail, but do we want this kind of behavior - to always have to use reregister?   

Not sure I understand what you mean by:
qq  So maybe it's only needed for the >`TcpListener` and not the other types? qq

**Comment by Thomasdezeeuw** [comment]
The patch in the comment https://github.com/tokio-rs/mio/issues/1074#issuecomment-548738990 is not the pr #1112 because it caused the CI to fail. But I didn't check what tests failed, so I speculated that maybe only the `TcpListener` needed to reregister on a successful I/O operation (mainly accept), while for other types this would result in an error.

**Comment by dtacalau** [comment]
@Thomasdezeeuw  I made a confusion here https://github.com/tokio-rs/mio/issues/1074#issuecomment-548842444 when verifying your patch with reregistering. I've checked the patch with test TcpListener::try_clone but not with my simpler test https://github.com/tokio-rs/mio/issues/1074#issuecomment-54850103.

I've rechecked, so, with the reregistering patch my test passes while the TcpListener::try_clone still fails, so I opened another issue https://github.com/tokio-rs/mio/issues/1126, to track the reregistering on succesful operation.

The TcpListener::try_clone still fails because while, for a given TcpListener, you can reregister on succesful operation (so reseting the user events) you don't have any mean to do the same thing for its clones. So, to fix it, we need to find a way to also reregister all clones on successful operation of a cloned instance of TcpListener. Either this, or come up with another solution to reset the events. I'm still looking for ideas.

**Comment by dtacalau** [comment]
@Thomasdezeeuw could you point me to a use case for TcpListener::try_clone method, so I could understand how is this method expected to be used and why is it needed? Thanks.

**Comment by Thomasdezeeuw** [comment]
I've used `TcpListener::try_clone` is the past to split accepting connections to different threads. For example when binding to a port it's not possible to bind to it again (without reuse_address/reuse_port options), so cloning/duplicating the socket is an easy way to accept connections from multiple threads.

**Comment by dtacalau** [comment]
On Windows, try_clone seems to be broken for TcpListener, TcpStream, maybe UDP, because a new clone will use a new SockState, so, with the current implementation, there can't be any relation between parent SockState and the clone SockState. With the current impl polling over clones will not work as expected, this doesn't seem an easy fix.

We've discussed about try_clone on Discord and the conclusion was that support for try_clone (TcpStream, TcpListener, UDP) will be dropped for 0.7, and the feature will be revisited in a future release. Couple of reasons behind this decision: Windows impl is broken; on Unix there is no defined behavior, there are differences between epoll/kqueue,  because it is just a dup fd; lso tokio doesn't use try_clone.
 
@carllerche @Thomasdezeeuw could you take care of updating the docs and release notes for try_clone?

**Comment by dtacalau** [comment]
@Thomasdezeeuw this can be closed.

**Comment by Thomasdezeeuw** [comment]
The `try_clone` methods have been removed from all types are they broken in various ways, see #1184 and #1178.
