### ISSUE TITLE
udp poll with edge hangs

### ISSUE THREAD

**Issue by Licenser** [tokio-rs/mio#1076]
When using edge as a PollOpt udp sockets stop randomly receiving data.

See the following example: https://github.com/Licenser/mio-udp it stops after a few seconds.

**Comment by Thomasdezeeuw** [comment]
With edge triggers you need to `recv` in a loop, please read https://docs.rs/mio/0.6.19/mio/struct.Poll.html#edge-triggered-and-level-triggered.

**Comment by Licenser** [comment]
Hi Thomas, thanks for the quick answer! I read the documentation a few times but that it wasn’t clear for me. I’m a bit confused too how to read in a loop since there is no try_recv for the UDP socket.

**Comment by Thomasdezeeuw** [comment]
`recv` (or `read` or `write`, or really any I/O operation) on a non-blocking socket is already a `try_I/O` function as it returns `EAGAIN` or `EWOULDBLOCK` "error" to indicate the socket is not ready to perform that I/O operation, in Rust (and Mio) this is translated into an `io::Error` of the [`io::ErroKind::WouldBlock`](https://doc.rust-lang.org/std/io/enum.ErrorKind.html#variant.WouldBlock) kind.

Edge triggers are special in that they only deliver a single event when an I/O operation is ready. Before it delivers another event the I/O socket must first be drained, i.e. read from until it returns a `WouldBlock` "error" (in case of readable events), only after that will it return another event.

Mio in general isn't the easiest thing to work with, mainly because the OS selector (e.g. `kqueue`/`epoll` on which Mio is build) isn't easy to work with. Have you looked at [Tokio](https://docs.rs/tokio) before? It provides a (much) easier to use interface. Hope this helps.

**Comment by Licenser** [comment]
Thanks! That makes perfect sense now :D. I have looked at Tokio but to be honest the current state of futures in rust scares me away from it, I'll sure revisit it once await is stable!

In the meantime, to make sure your time isn't wasted with answering a one off question, do you mind if I contribute a UDP server example to mio?

**Comment by Thomasdezeeuw** [comment]
Contributes are always welcome! Adding more examples sound goods.
