### ISSUE TITLE
Question: mio tcp example

### ISSUE THREAD

**Issue by goriunov** [tokio-rs/mio#1085]
Hi there, i was just reading mio tcp example which was added few days ago and was concerned / had questions  about  few things.

Does `connection.read(&mut buf) ` read till the end of available data ?  If it does then should we use `vec` to make sure we fill up whole data. And if it does not should we use loop till we read in to would_block and then move in to next available event.

Also looking at example it tries to write and read in one single go. I think it would be good to make it more real live example :)

Sorry if something about wrong. Thanks for your great work :)

**Comment by Thomasdezeeuw** [comment]
> Does `connection.read(&mut buf) ` read till the end of available data ?

Read only reads the bytes available at the time of the call, limited to the size of the buffer provided (in this case `buf.len()`). That said it really should do so in a loop because we're using edge triggers (pr is welcome :)).

> Also looking at example it tries to write and read in one single go. I think it would be good to make it more real live example :)

Not sure what you mean with this, but I just wanted to say it is possible to receive a single event with both readable and writable readiness, but I do believe it's platform dependent.
