### ISSUE TITLE
Need to copy readiness info out of Event, or else copy whole Event

### ISSUE THREAD

**Issue by uazu** [tokio-rs/mio#1256]
I'm trying to convert some existing code to 0.7.0-alpha.1.

In 0.6 when I handle an Event, I map the Token to a local handler and then pass on the readiness info from the Event to that handler for it to interpret. In 0.7.0, there is no separate readiness info, just methods `is_readable()` etc on the Event. So I am stuck. I cannot copy or clone the Event, and I cannot copy a Ready value out to pass on. Note that I'm passing this info on to an async handler, so it cannot be a borrow.

**Comment by Thomasdezeeuw** [comment]
I see to possible solutions for this.

1. Mio can implement `Clone` for `Event`. I believe this is possible for all currently supported platforms, but it might make it harder to port to a new platforms.
2. Create your own `Readiness` type and read all (interesting) statuses from `Event`, essentially the same type that Mio 0.6 provided.

I would suggest the second option because `Event` on `kqueue(2)` platforms (macOS, *BSDs) is quite big, see https://docs.rs/libc/0.2.66/i686-apple-darwin/libc/struct.kevent.html. An `Readiness` type could fit in 8 bits (1 bit for each `Event::is_*` method), so clone would be a lot cheaper.

@uazu what do you think?

**Comment by uazu** [comment]
Yes, probably that's the sensible solution (make my own Readiness type). I can't really restructure because I allow different tokens to be handled with different priority levels, so I'll always need some queuing of lower-priority events at least, so I'll still need to copy the readiness info somehow.

I'll close this for now, as I guess there is no action required on mio.
