### ISSUE TITLE
deregister question

### ISSUE THREAD

**Issue by kingluo** [tokio-rs/mio#1270]
`deregister` would remove all interests on the socket.
Is it possible to specify which interest (read or write) to be deregistered? Otherwise, the app should remember its interest to reregister, which is very inconvenient.

And, in the `register` method doc:

> Unless otherwise specified, the caller should assume that once an event source is registered with a Poll instance, it is bound to that Poll instance for the lifetime of the event source. This remains true even if the event source is deregistered from the poll instance using deregister.

what does it mean? The source will be bound to the same Poll instance forever once registered?

**Comment by Thomasdezeeuw** [comment]
> `deregister` would remove all interests on the socket.
> Is it possible to specify which interest (read or write) to be deregistered? Otherwise, the app should remember its interest to reregister, which is very inconvenient.

This is not possible. You'll need to remember the interests yourself, otherwise Mio would need to remember the interests which is unwanted overhead for use cases which don't need this functionality.

> 
> And, in the `register` method doc:
> 
> > Unless otherwise specified, the caller should assume that once an event source is registered with a Poll instance, it is bound to that Poll instance for the lifetime of the event source. This remains true even if the event source is deregistered from the poll instance using deregister.
> 
> what does it mean? The source will be bound to the same Poll instance forever once registered?

It means that once an event source is registered with a `Poll` instance it shouldn't be registered with another `Poll` instance. It is safe to register it with the same `Poll` instance.

**Comment by kingluo** [comment]
Thanks for your clarification.
