### ISSUE TITLE
"function [new] or associated item not found in" `mio::poll::Poll`

### ISSUE THREAD

**Issue by kulicuu** [tokio-rs/mio#1293]
mio version 0.7.0
rustc version 1.44.0-nightly 2020-03-28

```rust
use mio::event::Event;
use mio::{Events, Interest, Poll, Registry, Token};

fn main() {
    let mut poll = Poll::new();
}
```

produces error:
```
error[E0599]: no function or associated item named `new` found for struct `mio::poll::Poll` in the current scope
 --> examples\src\bin\sandboxTwelve\main.rs:5:26
  |
5 |     let mut poll = Poll::new();
  |                          ^^^ function or associated item not found in `mio::poll::Poll`
```

**Comment by kleimkuhler** [comment]
@kulicuu In your `Cargo.toml` you will need to specify the `os-poll` feature in order to have a working `Poll` implementation:

```
[dependencies]
mio = { version = "0.7.0", features = ["os-poll"] }
```

Without specifying that feature, `Poll` only acts like a shell.

For some more information, you can look at the [features](https://docs.rs/mio/0.7.0/mio/features/index.html) module.
