### ISSUE TITLE
MIO should not report out-of-band data as 'is_readable'.

### ISSUE THREAD

**Issue by piscisaureus** [tokio-rs/mio#1317]
As seen [here](https://github.com/tokio-rs/mio/blob/b15fc18458a79ef8a51f73effa92548650f4e5dc/src/sys/unix/selector/epoll.rs#L142).

This is a vector for denial-of-service attacks. For background, read https://github.com/sandstorm-io/sandstorm-website/blob/ccee81abb2968e8a0301b1a63e189be719bc02d7/_posts/2015-04-08-osx-security-bug.md.

**Comment by Thomasdezeeuw** [comment]
Thanks @piscisaureus for this, I didn't know about this. However I'm not sure I entirely agree. The blog post explicitly mentioned nginx isn't affected because it uses edge-triggered mode, which also true for Mio. So in the worst case scenario we can a single event, not an infinite loop.

If however we do bring back oneshot and level support (#1049) we should consider this. We should however clearly document that `EPOLLPRI` is checked on Linux. Perhaps we should also suggest setting `SO_OOBINLINE` when using level triggers (like libuv seems to have solved it: https://github.com/libuv/libuv/commit/e19089f7b14800d3f9bd74d9699e841e4b61a36d).

/cc @kleimkuhler @carllerche @asomers what do you guys think?
