### ISSUE TITLE
Is the 0.6.x branch totally dead or is there a chance of a deps update on there?

### ISSUE THREAD

**Issue by Stammark** [tokio-rs/mio#1323]
Hi all,

First of all, I'm sorry if I'm a bit clueless or if this is not the right place to raise this issue. I am new here (and to Rust in general) :D

So, I have recently been experimenting with building on the aarch64-pc-windows-msvc target and I have had build problems when compiling mio 0.6.x, because of the dependency on winapi 0.2.x. Support was added in this commit https://github.com/retep998/winapi-rs/commit/3792048cb07f9b762f8f0913293027759ea78db2 , which is obviously much much later than winapi 0.2.x!

I see that the new mio 0.7 is nicely upgraded to use the new api 0.3.x, so thank you guys for that! However, many "higher" crates still depend on mio 0.6.x (e.g. tokio) and my guess is that it might take time until they migrate to 0.7 and then even more time until that filters up to the likes of rls and rustbook. Until then all these cannot be compiled for aarch64-pc-windows-msvc.

As a workaround I have tried hacking mio 0.6.x locally to use winapi 0.3.x and miow 0.3 with some success by re-finding where type definitions are and one API change (https://docs.rs/miow/0.3.3/x86_64-pc-windows-msvc/miow/net/trait.TcpListenerExt.html#tymethod.accept_overlapped).

My question is: Is there a desire to deliver any fixes in a new release of the 0.6.x branch, or should I keep this as "informal" until the proper migration to 0.7 filters up to the big packages?

Cheers,
Stam

**Comment by Thomasdezeeuw** [comment]
Updating winapi 0.2.x -> 0.3.x would be considered a breaking change as I believe the API changed, so it would require a bump in the Mio version as well, that is what happened in Mio v0.7. So changing winapi to 0.3.x isn't going to happen for Mio v0.6. Tokio is switching to Mio 0.7, although I don't know when exactly.

Since the winapi commit you linked doesn't seem to involved (after a quick look) the easiest way (right now) might be to suggest applying that commit to winapi 0.2.x. We did something similar for Mio to support Illumos (#1294).

**Comment by Stammark** [comment]
Hi Thomas! Ah, I see, thanks for the info! 

In that case, I will try and hack together a winapi 0.2.x with aarch64 support as a workaround for now, while we wait and see when Tokio will get bumped to 0.7 (if I have time over the next few weeks I'll see if I can contribute to this).
