### ISSUE TITLE
Can we have UdpSocket::only_v6() back?

### ISSUE THREAD

**Issue by djc** [tokio-rs/mio#1424]
This used to be in 0.6, but was removed in 0.7. We're using it in Quinn to detect dual-stack sockets on darwin:

https://github.com/quinn-rs/quinn/blob/main/quinn/src/platform/unix.rs#L44

**Comment by Thomasdezeeuw** [comment]
Yes `UdpSocket::only_v6` can come back, but the problem is that currently Mio exposes the same API as std lib, which doesn't expose this function. If this is urgent I would accept a pr that implements this directly using libc, otherwise this can wait for Mio to be based on socket2 which is planned for v0.8, which may be a month or so away.
