### ISSUE TITLE
Make IoSource public

### ISSUE THREAD

**Issue by berkowski** [tokio-rs/mio#1460]
I'm trying to update the [mio-serial](https://github.com/berkowski/mio-serial) crate to the 0.7 API.  I've got access to the RawFd descriptors on unix for the serial port so it seems like the natural thing to do is wrap it with the IoSource stuct.  However, the 'os-ext' doesn't expose this outside of the crate.

Given the documentation for IoStruct it seems like it should be provided for other users to build from, is this not the case?

**Comment by Thomasdezeeuw** [comment]
I initially intended to make `IoSource` public, however it's not possible to implement it on Windows for other types that are currently exposed by Mio. Mainly because we use AFD on Windows which only supports the networking types we already support.

As an alternative you can use [`SourceFd`](https://docs.rs/mio/0.7.8/mio/unix/struct.SourceFd.html), which is also Unix specific but is public.

**Comment by berkowski** [comment]
Thanks.  Looks like SourceFd will fit the bill just fine.  The windows side already uses NamedPipe, so I can continue to use that in 0.7 as well
