### ISSUE TITLE
error: undefined reference to 'epoll_create1'

### ISSUE THREAD

**Issue by Dushistov** [tokio-rs/mio#1473]
I saw this bug after upgrade to tokio 1.0,
but it is also possible to introduce with mio but itself.

For (current master) 58e589fddeac03453ffe60718c64e2a582c12275 :

```
mio $ cargo test --all-features --target=armv7-linux-androideabi
io/src/sys/unix/selector/epoll.rs:34: error: undefined reference to 'epoll_create1'
          clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

I use such `.cargo/config`:
```
[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi16-clang++"
```

before that I used  mio 0.6.23 and all compiles for android just fine.

**Comment by Thomasdezeeuw** [comment]
According to https://github.com/android/ndk/issues/394, `epoll_create1` isn't defined for Android API < 21. Android API 21 was released in Android Lollipop (from 2014). Can you change your Android API target to be 21+?

**Comment by Dushistov** [comment]
>  Can you change your Android API target to be 21+?

I  suppose yes. Android 5.0 (API level 21) is good enough. Though I expected API level 16 by default, because of this is Rust stdlib requirements. May be add note about minimum API level  into mio/README.md ?

**Comment by Thomasdezeeuw** [comment]
> I suppose yes. Android 5.0 (API level 21) is good enough. Though I expected API level 16 by default, because of this is Rust stdlib requirements.

Mio and stdlib are unrelated.

> May be add note about minimum API level into mio/README.md ?

Good idea, created #1474.

**Comment by Thomasdezeeuw** [comment]
> Probably worth reimplementing Mio using `epoll_create` and `fcntl` to make tokio compatible with API 16.

Android 4.1, with API level 16, was released in 2012. I don't think we want to support an API that old.

**Comment by honsunrise** [comment]
@Thomasdezeeuw 
So, Why this [1575](https://github.com/tokio-rs/mio/pull/1575) not be accepted?

**Comment by honsunrise** [comment]
I just wanted to save everyone’s time, so I didn’t elaborate on the details, only revealing the essence of the problem. Our users also can’t upgrade the kernel because the chip manufacturer doesn’t provide support for higher versions of the kernel, and there are a lot of these network devices currently. 

Because of the community's previously hard-line stance on supporting the old kernel, we have been using `[patch.crates-io]` to solve the problem.

The only happy thing about the whole thing is that the patch is no longer necessary.
