### ISSUE TITLE
Use std::os::unix::net::SocketAddr instead of mio::net::SocketAddr

### ISSUE THREAD

**Issue by Thomasdezeeuw** [tokio-rs/mio#1527]
It's the same type. It's only implemented by us because we can't create `std::os::unix::net::SocketAddr`.

**Comment by Thomasdezeeuw** [comment]
We can do this in 1.61.

**Comment by Noah-Kennedy** [comment]
@Thomasdezeeuw is it confirmed to be stabilizing then?

**Comment by Thomasdezeeuw** [comment]
@Noah-Kennedy it's stabilised in https://github.com/rust-lang/rust/pull/94356.

**Comment by RealXuChe** [comment]
From #1605, I want to notice you that there may be a regression in the replacement: As you can see [here](https://github.com/rust-lang/rust/blob/3fdd578d72a24d4efc2fe2ad18eec3b6ba72271e/library/std/src/os/unix/net/addr.rs#L32), `std::os::unix::net::SocketAddr` doesn't support binding to a path with  `\0` in it, which means it doesn't support abstract Unix socket.

Of course, there's no reason for `std::os::unix::net::SocketAddr` to support abstract Unix socket, since abstract Unix socket is a Linux feature, and not in the Unix spec.

But mio has already supported abstract Unix socket, though it's a little buggy, like there's no conditional compilation to make it only work on Linux. 

So this replacement will possibly break the use of abstract Unix socket, I think we need to be careful on this.

(Sorry for my bad English)

**Comment by Thomasdezeeuw** [comment]
I think the support is still unstable, but it's should come at some point: https://doc.rust-lang.org/std/os/unix/net/struct.SocketAddr.html#method.from_abstract_namespace. Maybe we can create a pr to stabilise it.

**Comment by gustav3d** [comment]
That's a good idea indeed.
