### ISSUE TITLE
Make `CompletionPort` public?

### ISSUE THREAD

**Issue by Berrysoft** [tokio-rs/mio#1714]
I've noticed #1345, but I need less APIs. I would just like to have the public `CompletionPort` APIs.

Backgrounds: I'm the author of [tokio-iocp](https://github.com/Berrysoft/tokio-iocp/), a IOCP lib working on tokio runtime. However, the mio waits for the IOCP handle for infinite time, which causes my runtime stuck. I also need APIs to access mio from tokio runtime, and I will ask for it in the tokio repo.

**Comment by Darksonn** [comment]
> I also need APIs to access mio from tokio runtime, and I will ask for it in the tokio repo.

You wont get this. Mio is a non-1.x.y dependency, so it will not be available in the public API of Tokio.

**Comment by Berrysoft** [comment]
Then maybe it's time to abandon tokio:(

**Comment by Darksonn** [comment]
See https://github.com/tokio-rs/tokio/issues/3781 for related discussion on a windows equivalent for `AsyncFd`.

**Comment by Thomasdezeeuw** [comment]
@Berrysoft you can make your case for making `CompletionPort` public. However I do want to note that this time Mio's design is really based around `epoll`/`kqueue` design "try operation polling" rather than completion polling like IOCP or io_uring. So we had to wrangle IOCP a bit to make it all work.

> [..] However, the mio waits for the IOCP handle for infinite time, which causes my runtime stuck.

Perhaps this is something we can tackle directly instead?

**Comment by Thomasdezeeuw** [comment]
@Berrysoft any update on this?

**Comment by Thomasdezeeuw** [comment]
Alright, then I'm going to close this.
