### ISSUE TITLE
WakerRegistrar mentioned in comment is not present

### ISSUE THREAD

**Issue by psumbera** [tokio-rs/mio#1728]
https://github.com/tokio-rs/mio/blame/f6a20da1c81c2d56a78bc6f6832b9904b9215914/src/sys/unix/selector/poll.rs#L267

```
                        // Remove the interest which just got triggered
                        // the IoSourceState/WakerRegistrar used with this selector will add back
                        // the interest using reregister.
                        poll_fd.events &= !poll_fd.revents;
```

when I use `mio` within https://github.com/rust-lang/rustup on Solaris it does not reregister (and `rustup` doesn't download stuff)

Looking at `IoSourceState` (mentioned in the comment as well) it does reregistration just in case of error!?

https://github.com/tokio-rs/mio/blob/master/src/sys/unix/selector/poll.rs#L663

@jasta, where is `WakerRegistrar` and how is `reregistration` supposed to work?

**Comment by jasta** [comment]
Indeed, the comment must not have been updated after the big refactor.  The logic that this is referring to is the call to reregister in the same file under IoSourceState::do_io.  This happens through a wrapper around all I/O that checks for EWOULDBLOCK, which actually breaks in tokio for certain cases due to https://github.com/tokio-rs/tokio/issues/5866.

I'll send up a PR to fix the comments though.
