### ISSUE TITLE
Why do UDP tests use unsafe for recv_from() and advancing buffer?

### ISSUE THREAD

**Issue by pusateri** [tokio-rs/mio#945]
It would be nice to have some examples that use a Bytes buffer that don’t use unsafe. I can’t seem to find any examples that allow UDP socket recv_from() into a Bytes buffer which is handy for reading Big Endian.

**Comment by Thomasdezeeuw** [comment]
You can use [`Vec::resize`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.resize) to resize a buffer without using unsafe, or as you mentioned the Bytes crate. But as this also happens when dealing with the `Read` and `Write` traits, this isn't really a problem specific to UDP or Mio.

I do agree that an example without using unsafe would be nice, for which we would welcome a pr.

**Comment by pusateri** [comment]
Ok. Thanks for the feedback. I'll attempt to put together a pull request.

**Comment by carllerche** [comment]
UDP should include fns that use T: Buf to avoid the unsafe code.
